# -*- MakeFile -*-

CC = gcc
CFLAGS = -Wall -g

all: ex16.1 ex16.2 ex16.3 ex16.4 ex16.5 ex16.6 ex16.7

ex16.3: ex16.3.c
	$(CC) ex16.3.c -o ex16.3 -lm

clean:
	rm -f *.o
	rm -f ex16.1 ex16.2 ex16.3 ex16.4 ex16.5 ex16.6 ex16.7




