# -*- MakeFile -*-

#select the compiler and flags
CC = gcc
CFLAGS = -Wall -g

all: ex7.1 ex7.2 ex7.3 ex7.4 ex7.5 ex7.6 ex7.7 ex7.8 ex7.9 ex7.10 ex7.11

clean:
	rm -f ex7.1 ex7.2 ex7.3 ex7.4 ex7.5 ex7.6 ex7.7 ex7.8 ex7.9 ex7.10 ex7.11
