# -*- MakeFile -*-

CC = gcc
CFLAGS = -Wall -g

all: ex9.1 ex9.2 ex9.3 ex9.4 ex9.5 ex9.6 ex9.7 ex9.8 ex9.9 ex9.10 ex9.11

clean:
	rm -f ex9.1 ex9.2 ex9.3 ex9.4 ex9.5 ex9.6 ex9.7 ex9.8 ex9.9 ex9.10 ex9.11
